# -*- coding: utf-8 -*-
"""
Created on 2021-05-24 12:08:05
---------
@summary:
---------
@author: lscoo
"""

from feapder import Item


class DataParamsItem(Item):
    """
    This class was generated by feapder.
    command: feapder create -i data_params 1.
    """

    def __init__(self, *args, **kwargs):
        self.active_end_dttm = kwargs.get('active_end_dttm')
        self.active_start_dttm = kwargs.get('active_start_dttm')
        self.active_stop_flag = kwargs.get('active_stop_flag')
        self.begin_service_time = kwargs.get('begin_service_time')
        self.busNumber = kwargs.get('busNumber')
        self.data_source = kwargs.get('data_source')
        self.discount_count = kwargs.get('discount_count')
        self.discount_price = kwargs.get('discount_price')
        self.end_service_time = kwargs.get('end_service_time')
        self.fromCity = kwargs.get('fromCity')
        self.fromDate = kwargs.get('fromDate')
        self.fromStation = kwargs.get('fromStation')
        self.fromTime = kwargs.get('fromTime')
        self.fullPrice = kwargs.get('ticketUnitSalePrice')
        # self.gtime = kwargs.get('gtime')  # 抓取时间
        self.hashkey = kwargs.get('busNumber')
        # self.id = kwargs.get('id')  # id 自动递增
        self.phone_number = kwargs.get('phone_number')
        self.return_type = kwargs.get('return_type')
        self.serviceFee = kwargs.get('serviceFee')
        self.shift_type = kwargs.get('shift_type')
        self.symbol = kwargs.get('symbol')
        self.toCity = kwargs.get('toCity')
        self.toStation = kwargs.get('toStation')
        self.utmSource = kwargs.get('utmSource')
        self.vendor = kwargs.get('vendor')
        self.vendor_activity_flag = kwargs.get('vendor_activity_flag')
        self.vendor_activity_id = kwargs.get('vendor_activity_id')
