# -*- coding: utf-8 -*-
"""
Created on 2021-05-23 14:08:24
---------
@summary:
---------
@author: lscoo
"""

from feapder import Item


class XiechengDataRecordItem(Item):
    """
    This class was generated by feapder.
    command: feapder create -i spider_xiecheng_bus_list.
    """

    def __init__(self, *args, **kwargs):
        self._date = kwargs.get('_date')
        self._from = kwargs.get('_from')
        self._to = kwargs.get('_to')
        # self.id = None
        self.num = kwargs.get('num')
        self.page = kwargs.get('page')
        self.data_params = kwargs.get('data_params')
        self.value = kwargs.get('value')
        self.base_full_price = kwargs.get('base_full_price')
